spring:
   datasource:
      username: dog_rescue
      password: dog_rescue
      url: jdbc:mysql://localhost:3306/dog_rescue
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      
   sql:
      init:
         mode: never